(function(g){var window=this;'use strict';var ylb=function(a,b){a.Ra("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.nr(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Kg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.lN&&(b.lengthText?(e=b.lengthText||null,f=b.ww||null):b.lengthSeconds&&(e=g.gR(b.lengthSeconds),f=g.gR(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.$ya(d).type;var l=b instanceof g.lN?b.isLivePlayback:null,m=b instanceof g.lN?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,t=[],u=[];n&&t.push(n);p&&(t.push(p),u.push(p));q&&u.push(q);c={title:b.title,author:n,author_and_views:t.join(" \u2022 "),aria_label:b.ariaLabel||
g.kP("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Wk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:u.join(" \u2022 "),autoplayAlternativeHeader:b.Ks};b instanceof g.kN&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.X(),c=b.D;
g.Y.call(this,{I:"a",T:"ytp-autonav-suggestion-card",Z:{href:"{{url}}",target:c?b.ma:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Y:[{I:"div",Na:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Z:{style:"{{background}}"},Y:[{I:"div",Z:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],Ba:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],Ba:"Live"},{I:"div",
Na:["ytp-autonav-upcoming-stamp"],Ba:"Upcoming"},{I:"div",T:"ytp-autonav-list-overlay",Y:[{I:"div",T:"ytp-autonav-mix-text",Ba:"Mix"},{I:"div",T:"ytp-autonav-mix-icon"}]}]},{I:"div",Na:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Ba:"{{title}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Ba:"{{author}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Ba:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Ua("click",this.onClick);this.Ua("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.Y.call(this,{I:"div",T:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.G=void 0;this.C=0;this.container=new g.Y({I:"div",T:"ytp-autonav-endscreen-countdown-container"});g.H(this,this.container);this.container.Ka(this.element);b=a.X();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.V(a,"videodatachange",this.onVideoDataChange);this.j=new g.Y({I:"div",T:"ytp-autonav-endscreen-upnext-container",Z:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Y:[{I:"div",T:"ytp-autonav-endscreen-upnext-header"},{I:"div",T:"ytp-autonav-endscreen-upnext-alternative-header",Ba:"{{autoplayAlternativeHeader}}"},{I:"a",T:"ytp-autonav-endscreen-link-container",Z:{href:"{{url}}",target:d?b.ma:""},Y:[{I:"div",T:"ytp-autonav-endscreen-upnext-thumbnail",Z:{style:"{{background}}"},Y:[{I:"div",Z:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],
Ba:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],Ba:"Live"},{I:"div",Na:["ytp-autonav-upcoming-stamp"],Ba:"Upcoming"}]},{I:"div",T:"ytp-autonav-endscreen-video-info",Y:[{I:"div",T:"ytp-autonav-endscreen-premium-badge"},{I:"div",T:"ytp-autonav-endscreen-upnext-title",Ba:"{{title}}"},{I:"div",T:"ytp-autonav-endscreen-upnext-author",Ba:"{{author}}"},{I:"div",T:"ytp-autonav-view-and-date",Ba:"{{views_and_publish_time}}"},{I:"div",T:"ytp-autonav-author-and-view",Ba:"{{author_and_views}}"}]}]}]});
g.H(this,this.j);this.j.Ka(this.container.element);d||this.V(this.j.Ia("ytp-autonav-endscreen-link-container"),"click",this.YR);this.J.xb(this.container.element,this,115127);this.J.xb(this.j.Ia("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.Y({I:"div",T:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.Ka(this.container.element);this.B=new g.Y({I:"div",T:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.Ka(this.container.element);this.cancelButton=
new g.Y({I:"button",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{"aria-label":"Cancel auto-play"},Ba:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Ka(this.B.element);this.cancelButton.Ua("click",this.I0,this);this.J.xb(this.cancelButton.element,this,115129);this.playButton=new g.Y({I:"a",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{href:"{{url}}",role:"button","aria-label":"Play next video"},Ba:"Play now"});g.H(this,this.playButton);this.playButton.Ka(this.B.element);this.playButton.Ua("click",this.YR,this);this.J.xb(this.playButton.element,this,115130);this.D=new g.br(function(){zlb(c)},500);
g.H(this,this.D);this.XR();this.V(a,"autonavvisibility",this.XR);this.J.N("web_autonav_color_transition")&&(this.V(a,"autonavchange",this.H0),this.V(a,"onAutonavCoundownStarted",this.D7))},o6=function(a){var b=a.J.Vk(!0,a.J.isFullscreen());
g.nr(a.container.element,"ytp-autonav-endscreen-small-mode",a.Yg(b));g.nr(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.IJ);g.nr(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Bf());g.nr(a.J.getRootNode(),"countdown-running",a.Zk());g.nr(a.container.element,"ytp-player-content",a.J.Bf());g.yo(a.overlay.element,{width:b.width+"px"});if(!a.Zk()){a.J.Bf()?Alb(a,Math.round(Blb(a)/1E3)):Alb(a);b=!!a.suggestion&&!!a.suggestion.Ks;var c=a.J.Bf()||!b;
g.nr(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.nr(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.yQ(a.B,a.J.Bf());g.nr(a.element,"ytp-enable-w2w-color-transitions",Clb(a))}},zlb=function(a){var b=Blb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Alb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Zk()?a.select(!0):a.Zk()&&a.D.start()},Blb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.vB;return-1===a||void 0===a?8E3:a}return 0<=a.J.jt()?a.J.jt():g.TK(a.J.X().experiments,"autoplay_time")||1E4},Clb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},Alb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ia("ytp-autonav-endscreen-upnext-header");g.ef(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.cf("Up next in $SECONDS".slice(0,d)));var e=g.bf("span");g.hr(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.sf(e,b);a.appendChild(e);a.appendChild(g.cf("Up next in $SECONDS".slice(d+c.length)));return}}g.sf(a,"Up next")},p6=function(a,b){g.Y.call(this,{I:"div",
Na:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.Y.call(this,{I:"div",
Na:["ytp-upnext","ytp-player-content"],Z:{"aria-label":"{{aria_label}}"},Y:[{I:"div",T:"ytp-cued-thumbnail-overlay-image",Z:{style:"{{background}}"}},{I:"span",T:"ytp-upnext-top",Y:[{I:"span",T:"ytp-upnext-header",Ba:"Up Next"},{I:"span",T:"ytp-upnext-title",Ba:"{{title}}"},{I:"span",T:"ytp-upnext-author",Ba:"{{author}}"}]},{I:"a",T:"ytp-upnext-autoplay-icon",Z:{role:"button",href:"{{url}}","aria-label":"Play next video"},Y:[{I:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
Y:[{I:"circle",T:"ytp-svg-autoplay-circle",Z:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",T:"ytp-svg-autoplay-ring",Z:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",T:"ytp-svg-fill",Z:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",T:"ytp-upnext-bottom",Y:[{I:"span",T:"ytp-upnext-cancel"},{I:"span",T:"ytp-upnext-paused",
Ba:"Auto-play is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ia("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.br(this.rG,5E3,this);this.B=0;var b=this.Ia("ytp-upnext-cancel");this.cancelButton=new g.Y({I:"button",Na:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:"0","aria-label":"Cancel auto-play"},Ba:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Ua("click",this.J0,this);this.cancelButton.Ka(b);this.cancelButton&&this.api.xb(this.cancelButton.element,
this,115129);g.H(this,this.D);this.api.xb(this.element,this,18788);b=this.Ia("ytp-upnext-autoplay-icon");this.V(b,"click",this.K0);this.api.xb(b,this,115130);this.ZR();this.V(a,"autonavvisibility",this.ZR);this.V(a,"mdxnowautoplaying",this.m8);this.V(a,"mdxautoplaycanceled",this.n8);g.nr(this.element,"ytp-upnext-mobile",this.api.X().B)},Dlb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.vB;return-1===a||void 0===a?8E3:a}return 0<=a.api.jt()?a.api.jt():g.TK(a.api.X().experiments,"autoplay_time")||1E4},Elb=function(a,b){b=Dlb(a,b);
var c=Math,d=c.min;var e=(0,g.LC)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Zk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Zk()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.Y({I:"div",T:"ytp-suggestion-panel",Y:[{I:"div",Na:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Ba:"More videos"}]});this.S=new g.Y({I:"div",T:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new n6(this.player);g.H(this,this.B);this.B.Ka(this.element);a.getVideoData().We?this.j=this.B:(this.j=new q6(a),g.wS(this.player,this.j.element,4),g.H(this,this.j));this.overlay=new g.Y({I:"div",
T:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.Ka(this.element);this.D=new g.VJ(this);g.H(this,this.D);g.H(this,this.table);this.table.Ka(this.element);this.table.show();g.H(this,this.S);this.S.Ka(this.table.element);this.hide()},s6=function(a){var b=a.Bf();
b!==a.G&&(a.G=b,a.player.va("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},t6=function(a,b){g.Y.call(this,{I:"button",
Na:["ytp-watch-on-youtube-button","ytp-button"],Ba:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.updateButton();2===this.buttonType&&g.jr(this.element,"ytp-continue-watching-button");this.Ua("click",this.onClick);this.Ua("videodatachange",this.updateButton);g.yQ(this,!0)},u6=function(a,b){p6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.j=b;this.J.xb(this.element,this,156943);this.watchButton=new t6(a,2);g.H(this,this.watchButton);this.watchButton.Ka(this.element);this.hide()},Flb=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.Y({I:"div",T:"ytp-subscribe-card",Y:[{I:"img",T:"ytp-author-image",Z:{src:"{{profilePicture}}"}},{I:"div",T:"ytp-subscribe-card-right",Y:[{I:"div",T:"ytp-author-name",Ba:"{{author}}"},{I:"div",T:"html5-subscribe-button-container"}]}]});g.H(this,this.j);this.j.Ka(this.element);var b=a.getVideoData();this.subscribeButton=new g.jU("Subscribe",null,"Unsubscribe",null,!0,!1,b.Fk,b.subscribed,"trailer-endscreen",null,a);g.H(this,this.subscribeButton);this.subscribeButton.Ka(this.j.Ia("html5-subscribe-button-container"));
this.V(a,"videodatachange",this.Ta);this.Ta();this.hide()},v6=function(a){var b=a.X(),c=g.YJ||g.SL?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.Y.call(this,{I:"a",Na:e,Z:{href:"{{url}}",target:d?b.ma:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},Y:[{I:"div",T:"ytp-videowall-still-image",Z:{style:"{{background}}"}},{I:"span",T:"ytp-videowall-still-info",Z:{"aria-hidden":"true"},Y:[{I:"span",T:"ytp-videowall-still-info-bg",Y:[{I:"span",T:"ytp-videowall-still-info-content",Z:c,Y:[{I:"span",T:"ytp-videowall-still-info-title",Ba:"{{title}}"},
{I:"span",T:"ytp-videowall-still-info-author",Ba:"{{author_and_views}}"},{I:"span",T:"ytp-videowall-still-info-live",Ba:"Live"},{I:"span",T:"ytp-videowall-still-info-duration",Ba:"{{duration}}"}]}]}]},{I:"span",Na:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},Y:[{I:"span",T:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",T:"ytp-videowall-still-listlabel-length",Y:[" (",{I:"span",Ba:"{{playlist_length}}"},")"]}]},{I:"span",Na:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},Y:[{I:"span",T:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",T:"ytp-videowall-still-listlabel-length",Ba:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.VJ(this);g.H(this,this.j);this.Ua("click",this.onClick);this.Ua("keypress",this.onKeyPress);this.j.V(a,"videodatachange",this.onVideoDataChange);a.cg(this.element,this);this.onVideoDataChange()},w6=function(a){p6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.S=!1;this.W=null;this.B=new g.VJ(this);g.H(this,this.B);this.K=new g.br(function(){g.jr(b.element,"ytp-show-tiles")},0);
g.H(this,this.K);var c=new g.Y({I:"button",Na:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":"Previous"},Y:[g.CQ()]});g.H(this,c);c.Ka(this.element);c.Ua("click",this.O0,this);this.table=new g.vQ({I:"div",T:"ytp-endscreen-content"});g.H(this,this.table);this.table.Ka(this.element);c=new g.Y({I:"button",Na:["ytp-button","ytp-endscreen-next"],Z:{"aria-label":"Next"},Y:[g.DQ()]});g.H(this,c);c.Ka(this.element);c.Ua("click",this.N0,this);a.getVideoData().We?this.j=new n6(a,!0):this.j=new q6(a);
g.H(this,this.j);g.wS(this.player,this.j.element,4);a.xb(this.element,this,158789);this.hide()},x6=function(a){return g.xS(a.player)&&a.cC()&&!a.D},y6=function(a){var b=a.Bf();
b!==a.S&&(a.S=b,a.player.va("autonavvisibility"))},z6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t6(a,1);g.H(this,this.watchButton);this.watchButton.Ka(this.element);g.Rab(a)&&(this.j=new g.O2(a,g.fS(a)),g.H(this,this.j),this.B=new g.Y({I:"div",Na:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Z:{tabIndex:"-1"},Y:[this.j]}),g.H(this,this.B),this.j.Ka(this.B.element),this.B.Ka(this.element));a.xb(this.element,this,156914);this.hide()},Jlb=function(a){g.xT.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.VJ(this);g.H(this,this.listeners);var c=a.X(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.hB(g.cM(c))&&d&&!g.sS(a)?(this.B=!0,this.endScreen=new u6(a,g.fS(a))):g.tS(a)?this.endScreen=new z6(a):Glb(a)?(this.D=!0,Hlb(this),this.j?this.endScreen=new r6(a):this.endScreen=new w6(a)):c.Hh?this.endScreen=new Flb(a):this.endScreen=new p6(a);g.H(this,this.endScreen);g.wS(a,this.endScreen.element,4);Ilb(this);
this.listeners.V(a,"videodatachange",this.onVideoDataChange,this);this.listeners.V(a,g.SG("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.V(a,g.TG("endscreen"),function(e){b.onCueRangeExit(e)})},Hlb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Nl&&a.C===b.We)return!1;a.j=b.Nl;a.C=b.We;return!0},Glb=function(a){a=a.X();
return a.Rd&&!a.Hh},Ilb=function(a){a.player.Ue("endscreen");
var b=a.player.getVideoData();b=new g.RG(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.RG(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.jf([b,c])};
g.cW.prototype.QA=g.ca(37,function(a){this.FP!==a&&(this.FP=a,this.Kl())});
g.OU.prototype.Sr=g.ca(36,function(a){this.B!==a&&(this.B=a,this.Ta())});
g.cW.prototype.Sr=g.ca(35,function(a){this.shareButton&&this.shareButton.Sr(a)});
g.KU.prototype.Rr=g.ca(34,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.cW.prototype.Rr=g.ca(33,function(a){this.overflowButton&&this.overflowButton.Rr(a)});
g.aU.prototype.bF=g.ca(32,function(a){this.GP!==a&&(this.GP=a,this.aq())});
g.oS.prototype.jt=g.ca(6,function(){return this.app.jt()});
g.UZ.prototype.jt=g.ca(5,function(){return this.getVideoData().BT});g.x(m6,g.Y);m6.prototype.select=function(){this.J.Eo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.yC||void 0)&&this.J.ub(this.element)};
m6.prototype.onClick=function(a){g.OS(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.sP(a)||(this.select(),g.tP(a))}};g.x(n6,g.Y);g.k=n6.prototype;g.k.EF=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.updateValue("url",this.suggestion.Wk()),o6(this))};
g.k.Zk=function(){return 0<this.C};
g.k.YA=function(){this.Zk()||(this.C=Date.now(),zlb(this),ylb(this.J,Blb(this)),g.nr(this.J.getRootNode(),"countdown-running",this.Zk()))};
g.k.Mw=function(){this.Zr();zlb(this);var a=this.j.Ia("ytp-autonav-endscreen-upnext-header");a&&g.sf(a,"Up next")};
g.k.Zr=function(){this.Zk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Zr()};
g.k.YR=function(a){g.OS(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.ub(this.playButton.element):a.currentTarget===this.j.Ia("ytp-autonav-endscreen-link-container")&&(a=this.j.Ia("ytp-autonav-endscreen-link-container"),this.J.Za(a,!0),this.J.ub(a)),this.select())};
g.k.I0=function(){this.J.ub(this.cancelButton.element);g.qS(this.J,!0);this.G&&this.J.Ra("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){var c;this.G=null==(c=b.C3)?void 0:c.command};
g.k.D7=function(a){if(Clb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.nR(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.nR(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.nR(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.nR(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.nR(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.nR(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.nr(this.element,"ytp-w2w-animate",!0)}};
g.k.H0=function(a){this.J.N("web_autonav_color_transition")&&2!==a&&g.nr(this.element,"ytp-w2w-animate",!1)};
g.k.XR=function(){var a=this.J.Bf();this.K&&this.Gb!==a&&g.yQ(this,a);o6(this);this.J.Za(this.container.element,a);this.J.Za(this.cancelButton.element,a);this.J.Za(this.j.Ia("ytp-autonav-endscreen-link-container"),a);this.J.Za(this.playButton.element,a)};
g.k.Yg=function(a){return 400>a.width||459>a.height};g.x(p6,g.Y);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.cC=function(){return!1};
g.k.Bf=function(){return!1};
g.k.MW=function(){return!1};g.x(q6,g.Y);g.k=q6.prototype;g.k.rG=function(){this.notification&&(this.D.stop(),this.Mc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.EF=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.ZR=function(){g.yQ(this,this.api.Bf());this.api.Za(this.element,this.api.Bf());this.api.Za(this.Ia("ytp-upnext-autoplay-icon"),this.api.Bf());this.cancelButton&&this.api.Za(this.cancelButton.element,this.api.Bf())};
g.k.v8=function(){window.focus();this.rG()};
g.k.YA=function(a){var b=this;this.Zk()||(g.eE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.LC)(),this.j=new g.br(function(){Elb(b,a)},25),Elb(this,a),ylb(this.api,Dlb(this,a)));
g.lr(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.Y.prototype.hide.call(this)};
g.k.Zk=function(){return!!this.j};
g.k.Mw=function(){this.Zr();this.B=(0,g.LC)();Elb(this);g.jr(this.element,"ytp-upnext-autoplay-paused")};
g.k.Zr=function(){this.Zk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.X().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.rG(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Kg()}),this.C=this.V(this.notification,"click",this.v8),this.D.start())}this.Zr();this.api.nextVideo(!1,a)};
g.k.K0=function(a){!g.rf(this.cancelButton.element,g.rP(a))&&g.OS(a,this.api)&&(this.api.Bf()&&this.api.ub(this.Ia("ytp-upnext-autoplay-icon")),this.select())};
g.k.J0=function(){this.api.Bf()&&this.cancelButton&&this.api.ub(this.cancelButton.element);g.qS(this.api,!0)};
g.k.m8=function(a){this.api.getPresentingPlayerType();this.show();this.YA(a)};
g.k.n8=function(){this.api.getPresentingPlayerType();this.Zr();this.hide()};
g.k.ya=function(){this.Zr();this.rG();g.Y.prototype.ya.call(this)};g.x(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.D.V(this.player,"appresize",this.DB);this.D.V(this.player,"onVideoAreaChange",this.DB);this.D.V(this.player,"videodatachange",this.onVideoDataChange);this.D.V(this.player,"autonavchange",this.aS);this.D.V(this.player,"autonavcancel",this.L0);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.qS(this.player,!1);g.xS(this.player)&&this.cC()&&!this.C?(s6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.YA():3===this.videoData.autonavState&&this.j.Mw()):(g.qS(this.player,!0),s6(this));this.DB()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.Mw();s6(this)};
g.k.DB=function(){var a=this.player.Vk(!0,this.player.isFullscreen());s6(this);o6(this.B);g.nr(this.element,"ytp-autonav-cancelled-small-mode",this.Yg(a));g.nr(this.element,"ytp-autonav-cancelled-tiny-mode",this.MH(a));g.nr(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.yo(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.nr(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var b=g.QN(this.videoData);b&&(this.j.EF(b),this.j!==this.B&&this.B.EF(b))}if(a&&a.length)for(b=0;b<Klb.length;++b){var c=Klb[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.H(this,this.videos[b]);this.videos[b].Ka(this.S.element)}}this.DB()}};
g.k.aS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Zr(),this.Gb&&this.DB()):(this.K=!0,this.Bf()&&(2===a?this.j.YA():3===a&&this.j.Mw()))};
g.k.L0=function(a){a?this.aS(1):(this.C=null,this.K=!1)};
g.k.cC=function(){return 1!==this.videoData.autonavState};
g.k.Yg=function(a){return(910>a.width||459>a.height)&&!this.MH(a)&&!(400>=a.width||360>=a.height)};
g.k.MH=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Bf=function(){return this.Gb&&g.xS(this.player)&&this.cC()&&!this.C};
var Klb=[1,3,2,4];g.x(t6,g.Y);g.k=t6.prototype;
g.k.updateButton=function(){var a=this.J.getVideoData();if(this.J.N("embeds_enable_server_driven_watch_again_on_youtube")){var b,c;if(b=(a=null==(b=a.Ad)?void 0:null==(c=b.playerOverlays)?void 0:c.playerOverlayRenderer)&&g.Q(a.watchOnYoutubeButton,g.bNa))this.j=b}if(this.j)this.update({content:this.j.title}),this.J.rj(this.element)&&this.J.Yy(this.element),this.J.cg(this.element,this),this.J.gg(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:b="Watch again on YouTube";
c=156915;break;case 2:b="Continue watching on YouTube";c=156942;break;default:b="Continue watching on YouTube",c=156942}this.update({content:b});this.J.rj(this.element)&&this.J.Yy(this.element);this.J.xb(this.element,this,c)}};
g.k.onClick=function(a){this.J.N("web_player_log_click_before_generating_ve_conversion_params")&&this.J.ub(this.element);this.j?this.J.Ra("innertubeCommand",g.Q(this.j.onTap,g.sQ)):g.PS(this.getVideoUrl(),this.J,a);this.J.N("web_player_log_click_before_generating_ve_conversion_params")||this.J.ub(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.X();if(g.TL(b)||g.bM(b)){var c={};g.TL(b)&&g.dS(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.WR(c,b);a=g.gk(a,c)}return a};
g.k.Za=function(){this.J.Za(this.element,this.Gb&&this.ma)};
g.k.show=function(){g.Y.prototype.show.call(this);this.Za()};
g.k.hide=function(){g.Y.prototype.hide.call(this);this.Za()};
g.k.lc=function(a){g.Y.prototype.lc.call(this,a);this.Za()};g.x(u6,p6);u6.prototype.show=function(){3!==this.player.getPlayerState()&&(p6.prototype.show.call(this),this.j.QA(!0),this.j.Sr(!0),this.J.X().hc||this.j.Rr(!0),this.J.Za(this.element,!0),this.watchButton.lc(!0))};
u6.prototype.hide=function(){p6.prototype.hide.call(this);this.j.QA(!1);this.j.Sr(!1);this.j.Rr(!1);this.J.Za(this.element,!1);this.watchButton.lc(!1)};g.x(Flb,p6);Flb.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Fk;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.x(v6,g.Y);v6.prototype.select=function(){this.api.Eo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.yC||void 0)&&this.api.ub(this.element)};
v6.prototype.onClick=function(a){if(g.TL(this.api.X())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.ub(this.element);var b=this.suggestion.Wk(),c={};g.mMa(this.api,c,"emb_rel_end");b=g.gk(b,c);g.PS(b,this.api,a)}else g.OS(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
v6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.sP(a)||(this.select(),g.tP(a))}};
v6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.X();this.B=a.Gd?!1:b.D};g.x(w6,p6);g.k=w6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.eq();this.B.V(this.player,"appresize",this.eq);this.B.V(this.player,"onVideoAreaChange",this.eq);this.B.V(this.player,"videodatachange",this.onVideoDataChange);this.B.V(this.player,"autonavchange",this.sK);this.B.V(this.player,"autonavcancel",this.M0);a=this.videoData.autonavState;a!==this.W&&this.sK(a);this.B.V(this.element,"transitionend",this.J9)};
g.k.destroy=function(){g.DB(this.B);g.rb(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.lr(this.element,"ytp-show-tiles");this.K.stop();this.W=this.videoData.autonavState};
g.k.cC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Gb;p6.prototype.show.call(this);g.lr(this.element,"ytp-show-tiles");this.player.X().B?g.dr(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.qS(this.player,!1);x6(this)?(y6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.YA():3===this.videoData.autonavState&&this.j.Mw()):(g.qS(this.player,!0),y6(this));a!==this.Gb&&this.player.Za(this.element,!0)};
g.k.hide=function(){var a=this.Gb;p6.prototype.hide.call(this);this.j.Mw();y6(this);a!==this.Gb&&this.player.Za(this.element,!1)};
g.k.J9=function(a){g.rP(a)===this.element&&this.eq()};
g.k.eq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.QN(d)];if(e.length){g.jr(this.element,"ytp-endscreen-paginate");var f=this.J.Vk(!0,this.J.isFullscreen());if(a=g.fS(this.J))a=a.Mg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,t=b/2,u=a<=l-2&&p>=t*n,y=b<=m-2&&p>=q*n;if((q+1)/t*d/h>h/(q/(t+1)*d)&&y)p-=q*n,b+=2;else if(u)p-=t*n,a+=2;else if(y)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Io(f,n,p);g.yo(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.EF(g.QN(this.videoData));this.j instanceof
n6&&o6(this.j);g.nr(this.element,"ytp-endscreen-takeover",x6(this));y6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,u=0,d&&l>=a-2&&m>=b-2?u=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(u=2):u=2),q=g.re(q+this.C,c),0!==u){t=this.stills[h];t||(t=new v6(this.player),this.stills[h]=t,f.appendChild(t.element));y=Math.floor(p*m/b);var A=Math.floor(n*l/a),E=Math.floor(p*(m+u)/b)-y-4,L=Math.floor(n*(l+u)/a)-A-4;g.Eo(t.element,A,y);g.Io(t.element,L,E);g.yo(t.element,"transitionDelay",
(m+l)/20+"s");g.nr(t.element,"ytp-videowall-still-mini",1===u);g.nr(t.element,"ytp-videowall-still-large",2<u);u=Math.max(L,E);g.nr(t.element,"ytp-videowall-still-round-large",256<=u);g.nr(t.element,"ytp-videowall-still-round-medium",96<u&&256>u);g.nr(t.element,"ytp-videowall-still-round-small",96>=u);q=e[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.X(),y=g.ir(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(t,q,y),g.TL(u)&&!t.api.N("web_player_log_click_before_generating_ve_conversion_params")&&
(u=q.Wk(),y={},g.dS(t.api,"addEmbedsConversionTrackingParams",[y]),u=g.gk(u,g.WR(y,"emb_rel_end")),t.updateValue("url",u)),(q=(q=q.sessionData)&&q.itct)&&t.api.gg(t.element,q));h++}f.ariaBusy="false";g.nr(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.gf(a.element),g.qb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.eq())};
g.k.N0=function(){this.C+=this.stills.length;this.eq()};
g.k.O0=function(){this.C-=this.stills.length;this.eq()};
g.k.MW=function(){return this.j.Zk()};
g.k.sK=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Zr(),this.Gb&&this.eq()):(this.G=!0,this.Gb&&x6(this)&&(2===a?this.j.YA():3===a&&this.j.Mw()))};
g.k.M0=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.Za(this.stills[a].element,!0);this.sK(1)}else this.D=null,this.G=!1;this.eq()};
g.k.Bf=function(){return this.Gb&&x6(this)};g.x(z6,p6);z6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a=this.B;if(a){var b=0<this.j.suggestionData.length;g.nr(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.fS(this.player))||c.bF(!0);this.player.Za(this.element,!0);this.watchButton.lc(!0)}};
z6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.fS(this.player))||a.bF(!1);this.player.Za(this.element,!1);this.watchButton.lc(!1)};g.x(Jlb,g.xT);g.k=Jlb.prototype;g.k.Yw=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.tS(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.QN(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Glb(this.player)||d;a=a.xj||g.bM(a.Ja);c=this.player.KC();return d&&!a&&!c&&!b};
g.k.Bf=function(){return this.endScreen.Bf()};
g.k.k6=function(){return this.Bf()?this.endScreen.MW():!1};
g.k.ya=function(){this.player.Ue("endscreen");g.xT.prototype.ya.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Fb().Te.get("heartbeat"),d=g.QN(a);!d||b.videoId!==d.videoId||a.JR?(this.player.Eo(b.videoId,void 0,void 0,!0,!0,b),c&&c.TH("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.xT.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.xT.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Yw()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Ilb(this);this.D&&Hlb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new w6(this.player),g.H(this,this.endScreen),g.wS(this.player,this.endScreen.element,4))};g.wT("endscreen",Jlb);})(_yt_player);
