(function(g){var window=this;'use strict';var qib=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},rib=function(a,b){var c=new g.FM;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},sib=function(a,b){var c,d,e;
return g.Ha(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.gD(),2);if(3!=f.j){d=f.B;if(!d)throw g.vC("gct");return g.z(f,g.sN(d),3)}e=f.B;return f.return(e.get("captions",c))})},tib=function(a,b,c){sib(a,b).then(function(d){d&&c(d.trackData,new g.FM(d.metadata))})},wib=function(a){if(!uib.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(vib,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},xib=function(){return g.IB("yt-player-caption-display-settings")},W4=function(){this.segments=[]},yib=function(a,b){var c=g.Tb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Gb(a.segments,c),g.Gb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Ob(a.segments,c,0,b),g.Ob(a.segments,c+1,0,b)))},zib=function(a,b,c,d,e,f){g.G.call(this);
this.policy=a;this.player=b;this.ma=c;this.onLoadCallback=d;this.G=e;this.W=f;this.D=new W4;this.K=-1;this.C=this.B=this.j=null;this.S=new g.br(this.bX,1E3,this);this.events=new g.VJ(this);g.H(this,this.S);g.H(this,this.events);this.events.V(b,"SEEK_COMPLETE",this.pA);this.pA();this.bX()},Aib=function(a){return a.j&&a.j.C?a.j.C+a.player.Jd()<a.player.getCurrentTime():!1},Bib=function(a,b){var c=g.Aua(b,a.policy,{}).lf(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ha){d.method="POST";var e=b.Dt(),f=(0,g.$X)([120,0]);e&&g.eN(e,g.fOa);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.BA(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.B){var l=!(a.G?h.response:h.responseText)||400<=h.status,m=g.Jva(h);if(m){h=g.Aua(a.B,a.policy,{});a.B.Xk(h,m);Bib(a,a.B);break a}if(l)a.player.Aa("capfail",{status:h.status});else if(a.player.ji().Ii("fcb_r"),m=a.B.ib[0].Qa,null!=a.onLoadCallback&&a.K!==m){l=a.B.ib[0];if(a.G)a.onLoadCallback(h.response,
1E3*(l.startTime+a.player.Jd()));else a.onLoadCallback(h.responseText,1E3*(l.startTime+a.player.Jd()));a.K=m}}a.B=null;a.C=null}}).Dk(function(h){a.B=null;
a.C=null;var l;a.player.Aa("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.B=b;yib(a.D,a.B.ib[0].Qa)},X4=function(a,b){g.AT.call(this,b.X());
this.B=a;this.J=b;this.C=null;this.G=!1;this.K=g.oM(this.J.X())&&!this.B.isManifestless},Dib=function(a,b){var c=[],d;
for(d in a.B.j)if(a.B.j.hasOwnProperty(d)){var e=a.B.j[d];if(g.GOa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.X().N("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.qgb.get(e);null==q&&(q=Cib[e]||Cib[e.replace(/-/g,"_")],g.qgb.set(e,q));h=q||h}c.push(new g.FM({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Eib=function(a,b){return null!=b&&b in a.B.j?a.B.j[b]:null},Fib=function(a,b,c){var d=[],e;
for(e in a.B.j)if(a.B.j.hasOwnProperty(e)){var f=a.B.j[e];if(g.GOa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},Hib=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in Gib?Gib.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={BD:c.BD};c.BD=d;var e=function(f){return function(){return String(a[f.BD])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.BD+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.BD,"gi"),e)}return b},Y4=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.Ye);a.params.Ye&&Object.assign(q,a.params.Ye);Object.assign(q,c.Ye);p.Ye=q;var t=1===p.Hi,u=[{I:"span",T:"captions-text",Z:{style:"word-wrap: normal; display: block;"}}],y,A,E;(l=l.rb("caption_edit_on_hover")&&(null==(y=n.getVideoData().getPlayerResponse())?void 0:null==(A=y.captions)?void 0:null==(E=A.playerCaptionsTracklistRenderer)?void 0:E.openTranscriptCommand))&&u.unshift({I:"button",T:"caption-edit",
Z:{tabindex:"0","aria-label":Hib()},Y:[{I:"svg",Z:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Y:[{I:"path",Z:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.Y.call(this,{I:"div",T:"caption-window",Z:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:p.lang},Y:u});var L=this;this.K=[];this.Ga=!1;this.B=a;this.Pa=
this.Oa=null;this.playerWidth=f;this.playerHeight=h;this.S=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=p;this.xd=c;this.Ca=b;this.D=this.Ia("captions-text");this.yc=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Va=Iib(d,e,f,h);this.Rc=m;l&&(this.G=this.Ia("caption-edit"),this.V(this.G,"click",function(){L.Rc()}));
this.type=0;this.kb=this.Va*Jib(q);a=new g.aT(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.E0,this);a.subscribe("dragmove",this.D0,this);a.subscribe("dragend",this.C0,this);this.sb=this.ob=this.Cb=this.wb=0;a="";this.j.windowOpacity&&(a=wib(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":Kib[this.j.textAlign]};this.yc&&(b["border-radius"]=a?this.kb/8+"px":"");(this.C=2===this.B.params.Hi||
3===this.B.params.Hi)&&Lib(this,this.element);g.yo(this.element,b);switch(this.j.fm){case 0:case 1:case 2:g.jr(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.jr(this.element,"ytp-caption-window-bottom")}},Lib=function(a,b){var c="vertical-rl";
1===a.j.cR&&(c="vertical-lr");g.Pe&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.yo(b,"-o-writing-mode",c);g.yo(b,"-webkit-writing-mode",c);g.yo(b,"writing-mode",c);g.yo(b,"text-orientation","upright");g.jr(b,"ytp-vertical-caption");3===a.B.params.Hi&&(g.yo(b,"text-orientation",""),g.yo(b,"transform","rotate(180deg)"))},Jib=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Mib=function(a,b){var c={},d=b.background?b.background:a.j.Ye.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Ye.backgroundOpacity;d=wib(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.yc&&(c["box-decoration-break"]="clone",c["border-radius"]=a.kb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Va*Jib(b)+"px";d=1;e=b.color||a.j.Ye.color;if(b.color||null!=b.textOpacity)e=wib(e),d=null==b.textOpacity?a.j.Ye.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.WL&&(h=e=b.WL);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.PA()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Ye.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.X5&&(c.visibility="hidden");1===b.pW&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.qM||g.tC,3===a.B.params.Hi?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.po||2===b.po||3===b.po||4===b.po||5===b.po)if(g.qM)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.po){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Nib=function(a){a.S=g.bf("SPAN");
g.yo(a.S,{display:"block"});g.jr(a.S,"caption-visual-line");a.D.appendChild(a.S)},Oib=function(a,b){var c=g.bf("SPAN");
g.yo(c,{display:"inline-block","white-space":"pre-wrap"});g.yo(c,Mib(a,b));c.classList.add("ytp-caption-segment");a.S.appendChild(c);c.previousElementSibling&&(g.yo(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.yo(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Pib=function(a,b,c){a.Ga=a.Ga||!!c;
var d={};Object.assign(d,a.j.Ye);Object.assign(d,c||b.j);Object.assign(d,a.xd.Ye);(c=!a.S)&&Nib(a);for(var e=a.Oa&&a.Pa&&g.kd(d,a.Pa)?a.Oa:Oib(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Nib(a),e=Oib(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.cf(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.qM||!g.Ao(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Ao(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Oc?g.yo(e,m,"1em"):g.yo(e,m,"0.5em")))}a.Pa=d;a.Oa=e;a.K.push(b)},Iib=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},Z4=function(a,b,c,d){g.AT.call(this,a);
this.videoData=b;this.audioTrack=c;this.bb=d;this.D=b.TL},$4=function(a,b,c,d,e,f,h,l,m,n){Y4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},a5=function(a,b,c,d,e,f,h,l,m,n){Y4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.W=[];this.ra=this.qa=this.Ya=0;this.Ha=NaN;this.hc=0;this.zc=null;this.fb=new g.br(this.a9,433,this);this.G&&(n.xb(this.G,this,167342),this.V(this.G,"click",function(){n.ub(p.G)}),a=new g.aT(this.element,!0),g.H(this,a),a.subscribe("hoverstart",function(){n.Za(p.G,!0)},this));
g.jr(this.element,"ytp-caption-window-rollup");g.H(this,this.fb);g.yo(this.element,"overflow","hidden")},Qib=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.cR&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Rib=function(a){a.W=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Mr,c=0,d=0,e=a.W.length-1;c<b&&-1<e;){var f=a.W[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.W.length<b&&(d*=b/a.W.length);a.qa=d;b=Math;c=b.max;isNaN(a.Ha)&&((d=a.j.Qs)?(e=g.bf("SPAN"),g.sf(e,"\u2013".repeat(d)),g.yo(e,Mib(a,a.j.Ye)),a.D.appendChild(e),a.Ha=e.offsetWidth,a.D.removeChild(e)):a.Ha=0);d=a.D;a.ra=c.call(b,a.Ha,a.hc,(a.C?d.offsetHeight:d.offsetWidth)+1)},Sib=function(a,b){Rib(a);
var c=a.W.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.qa-c;if(c!==a.Ya){var d=0<c&&0===a.Ya;b||isNaN(c)||d||(g.jr(a.element,"ytp-rollup-mode"),g.cr(a.fb));g.yo(a.D,"transform",Qib(a,c));a.Ya=c}Rib(a)},b5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.RG.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},c5=function(a,b,c,d,e){g.RG.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Tib=function(a){var b="_"+d5++;
return new c5(0,0x8000000000000,0,b,a)},Vib=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.fg){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Uib(l.textContent,n.textContent,p.textContent,f.textContent,h);return new b5(a,b,e,c,l,d,m)}switch(m.fg){case 9:case 10:m.po=1;break;case 11:m.po=2;break;case 12:m.po=3;break;case 13:m.po=4;break;case 14:m.po=5}return new b5(a,b,e,c,l.textContent||"",d,m)},Uib=function(a,b,c,d,e){var f=g.PA(),h=
f?g.bf("DIV"):g.bf("RUBY"),l=g.bf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.bf("DIV"):g.bf("RP");a.textContent=b;h.appendChild(a);b=f?g.bf("DIV"):g.bf("RT");b.textContent=c;h.appendChild(b);c=e.fg;if(10===c||11===c||12===c||13===c||14===c)if(g.yo(b,"text-emphasis-style","filled circle"),g.yo(b,"text-emphasis-color","currentcolor"),g.yo(b,"webkit-text-emphasis","filled circle"),11===e.fg||13===e.fg)g.yo(b,"webkit-text-emphasis-position","under left"),g.yo(b,"text-emphasis-position","under left");c=!0;if(4===e.fg||7===e.fg||12===e.fg||
14===e.fg)g.yo(h,"ruby-position","over"),g.yo(h,"-webkit-ruby-position","before");else if(5===e.fg||6===e.fg||11===e.fg||13===e.fg)g.yo(h,"ruby-position","under"),g.yo(h,"-webkit-ruby-position","after"),c=!1;e=f?g.bf("DIV"):g.bf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.yo(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.yo(f,"display","none"),f=f.nextElementSibling,g.yo(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.yo(h.lastElementChild,"display","none"),d?(g.yo(h,"padding-top","0.6em"),g.yo(f,"top","0")):(g.yo(h,"padding-bottom","0.6em"),g.yo(f,"bottom","0")));return h},e5=function(){g.G.apply(this,arguments)},f5=function(a){e5.call(this);
this.D=a;this.pens={};this.W={};this.ma={};this.G="_"+d5++;this.S={};this.C=this.j=null;this.K=!0},g5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},h5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},i5=function(a,b){a=g5(a,b);
return void 0!==a?a:null},k5=function(a,b){a=a.getAttribute(b);
if(null!=a)return j5.test(a),a},Wib=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.ma[d]:a.D);a=i5(b,"mh");null!=a&&(c.eA=a);a=i5(b,"ju");null!=a&&(c.textAlign=a);a=i5(b,"pd");null!=a&&(c.Hi=a);a=i5(b,"sd");null!=a&&(c.cR=a);a=k5(b,"wfc");null!=a&&(c.windowColor=a);b=g5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Xib=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.W[d]);a=i5(b,"ap");null!=a&&(c.fm=a);a=g5(b,"cc");null!=a&&(c.Qs=a);a=g5(b,"ah");null!=a&&(c.jk=a);a=g5(b,"rc");null!=a&&(c.Mr=a);b=g5(b,"av");null!=b&&(c.qo=b);return c},Yib=function(a,b,c,d){var e={};
Object.assign(e,Xib(a,b));Object.assign(e,Wib(a,b));d?g.kd(e,a.D)?(d=a.G,e=a.D):d="_"+d5++:d=b.getAttribute("id")||"_"+d5++;a=g5(b,"t")+c;b=g5(b,"d")||0x8000000000000;if(2===e.Hi||3===e.Hi)c=e.Mr,e.Mr=e.Qs,e.Qs=c;return new c5(a,b,0,d,e)},l5=function(a){e5.call(this);
this.K=a;this.j=new Map;this.D=new Map;this.G=new Map;this.C=new Map},m5=function(a){a=g.qe(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Zib=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.G.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Mr=a);b=b.ccColCount;void 0!==b&&(f.Qs=b);if(2===f.Hi||3===f.Hi)b=f.Mr,f.Mr=f.Qs,f.Qs=b;return new c5(c,d,0,e,f)},ajb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new $ib(this);this.G=new $ib(this);this.j=[];this.clear()},cjb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{qv:a,
Ls:b,result:0};a=bjb[a];b=bjb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ie()&&c.Ls===d;if(d)return{qv:a,Ls:b,result:1}}else if(b&128&&1<=a&&31>=a)return{qv:a,Ls:b,result:2};return{qv:a,Ls:b,result:3}},ejb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,djb(a.D,b,c,d))},fjb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.v(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?ejb(a,d.tU,d.uU,b):1===d.type&&a.B&496&&djb(a.G,d.tU,d.uU,b);a.j.length=0},n5=function(){this.type=0},o5=function(){this.state=this.Ls=this.qv=0},gjb=function(){this.timestamp=this.j=0},p5=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new n5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new gjb}},q5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},ljb=function(a,b){switch(a){case 0:return hjb[(b&127)-32];
case 1:return ijb[b&15];case 2:return jjb[b&31];case 3:return kjb[b&31]}return 0},r5=function(a){return a.B[a.row][a.col]},s5=function(a,b,c){2<=b&&1<a.col&&(--a.col,r5(a).j=0);
var d=r5(a);d.timestamp=a.D.time+0;d.j=ljb(b,c);32>a.col&&a.col++},mjb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},t5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},njb=function(a){a.row=0<a.j?a.j:1;
a.col=1;t5(a,0,15)},ojb=function(a){this.C=a;
this.G=0;this.style=new n5;this.K=new p5(this.C);this.S=new p5(this.C);this.text=new p5(this.C);this.B=this.K;this.D=this.S;this.j=this.B},pjb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(q5(d,c),njb(a.B),njb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(q5(d,c),t5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},qjb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},rjb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},$ib=function(a){this.j=a;
this.G=0;this.C=new ojb(this.j);this.K=new ojb(this.j);this.B=new o5;this.D=this.C},djb=function(a,b,c,d){a.B.update();
b=cjb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.qv;c=b.Ls;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&s5(a,0,b),c&96&&s5(a,0,c),0!==b&&0!==c&&3===a.style.type&&q5(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.qv=e,b.Ls=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(4!==b.style.type?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;mjb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));t5(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:s5(b.j,0,32);break a;case 48:57===c?(d=b.j,r5(d).j=0,32>d.col&&d.col++):s5(b.j,1,c&15)}break;case 2:c&32&&s5(b.j,2,c&31);break;case 3:c&32&&s5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:qjb(b);
break;case 33:d=b.j;1<d.col&&(--d.col,r5(d).j=0);break;case 36:d=b.j;b=r5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:pjb(b,2,d);break;case 38:pjb(b,3,d);break;case 39:pjb(b,4,d);break;case 40:s5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);njb(d);rjb(b);break;case 43:rjb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:q5(a,
d)}t5(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.col=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;q5(a,d);mjb(a,b,b+1,a.j-1);t5(a,a.row,1)}break;case 46:t5(b.D,0,15);break;case 47:q5(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,qjb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.col+=c&3)&&(d.col=32)}}},sjb=function(){},u5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},v5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},w5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},x5=function(a,b){e5.call(this);
this.C=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.j=new ajb;this.j.B=1<<this.track},ujb=function(a){if("string"===typeof a)return!1;
a=new u5(a,8,0);return tjb(a)},tjb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==w5(a))return!1;
a.version=v5(a);if(1<a.version)return!1;v5(a);v5(a);v5(a);return!0},y5=function(){e5.call(this)},vjb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new b5(b,c,d,e.id,p.nodeValue,f||0<n,g.ed(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);vjb(a,b,c,d,e,!0,p,q,m)}}},wjb=function(a){var b=a.split(":");
a=0;b=g.v(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},xjb=function(a,b,c,d){d=Object.assign({eA:0},d);
return new c5(a,b,c,"_"+d5++,d)},z5=function(a,b){g.G.call(this);
this.J=a;this.ea=b;this.parser=null;this.j=this.J.pz()},Djb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=yjb(a,b,d),l=[];try{for(var m=g.v(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.UQ;l="string"!==typeof q?l.concat(zjb(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(Ajb(a,q,t)):l.concat(Bjb(a,c,q,t))}var u=l}catch(y){g.xG(y),a.clear(),u=[]}if(0!==u.length)return u}b=Cjb(b);if(!b)return[];try{return"string"!==typeof b?zjb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?Ajb(a,b,d):Bjb(a,c,b,d)}catch(y){return g.xG(y),a.clear(),[]}},Cjb=function(a){if("string"===
typeof a||ujb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.II(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.wI(a)},yjb=function(a,b,c){if("string"===typeof b||ujb(b))return[{trackData:b,
UQ:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Yta(d);if(a.j&&e){var f=g.Pta(e),h=g.Qta(e);e=e.j;f&&e&&a.j.sF(e,f,h)}a=g.PI(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.wI(e),f.push({trackData:e,UQ:c+1E3*h});Ejb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Ejb=function(a,b,c){var d=g.II(a,0,1836476516),e=9E4;
d&&(e=g.JI(d)||9E4);d=0;for(var f=g.PI(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.II(a,l.dataOffset,1953653094))&&(l=g.II(a,l.dataOffset,1952867444))&&(l=g.Vta(l)/e*1E3,0===h&&(d=l),b[h].UQ=l-d+c||c*h*1E3)}},zjb=function(a,b,c,d,e){if(!ujb(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new x5(e,b));return a.parser.B(c,d)},Ajb=function(a,b,c){a.parser||(a.parser=new y5);
a=a.parser.B(b,c);.01>Math.random()&&g.yG(Error("Deprecated subtitles format in web player: WebVTT"));return a},Bjb=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new l5(Fjb(b))),a.parser.B(c,d)}catch(f){return g.xG(f),[]}var e=g.Qab(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new f5(Fjb(b),a.ea)),a.parser.B(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Fjb=
function(a){var b={};
if(a=g.IM(a))b.lang=a,g.Scb.test(a)&&(b.Hi=1);return b},A5=function(a){g.xT.call(this,a);
var b=this;this.J=a;this.ea=this.J.X();this.videoData=this.J.getVideoData();this.wb=this.J.qb();this.C={Ye:{}};this.G={Ye:{}};this.Ga=[];this.ra={};this.Ya={};this.qa=!1;this.yc=g.qO(this.videoData);this.ob=g.HOa(this.videoData,this.J);this.hc=!!this.videoData.captionTracks.length;this.zc=!!this.videoData.Id;this.fb="3"===this.ea.controlsType;this.j=this.S=this.W=this.Va=this.sb=null;this.kb=new z5(this.J,this.ea);this.B=null;this.Ha=new g.VJ(this);this.K=new g.Y({I:"div",T:"ytp-caption-window-container",
Z:{id:"ytp-caption-window-container"}});this.ma={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.hs("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Wr(d));this.storage=c;var e;this.Cb=!(null==(e=a.Re())||!e.lF());this.D=Gjb(this);this.Ca=!this.D&&this.fb&&this.Cb&&this.ob;g.H(this,this.kb);this.D?this.Pa=this.Oa=null:(this.Oa=new g.$q(this.uR,void 0,this),g.H(this,this.Oa),this.Pa=new g.br(this.w$,2E3,this),g.H(this,this.Pa));g.H(this,this.Ha);g.wS(this.player,this.K.element,
4);g.H(this,this.K);this.D||this.Ha.V(a,"resize",this.wR);(this.Vb=g.XL(this.ea)&&!g.pB()&&!this.J.isFullscreen()&&!this.D&&!this.Ca)&&this.Ha.V(a,"resize",this.k8);this.Ha.V(a,"onPlaybackAudioChange",this.C7);this.Ha.V(a,g.SG("captions"),function(f){b.onCueRangeEnter(f)});
this.Ha.V(a,g.TG("captions"),function(f){b.onCueRangeExit(f)});
Hjb(this,xib()||{});this.player.Ra("onCaptionsModuleAvailable")},Kjb=function(a){if(1===a.ea.yc||1===a.videoData.rE||"alwayson"===g.ZN(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().B;if(2===a.ea.yc){if(g.mM(a.ea))var c=Ijb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=qib(a.player.getAudioTrack(),g.mM(a.ea));var d=g.ZN(a.videoData,"yt:cc");if(void 0===Jjb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.ZN(a.videoData,"yt:cc")},B5=function(a,b){if(a.B&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.B},Jjb=function(a){var b=void 0,c=g.PB(g.OB(),65);
if(g.mM(a.ea)&&null!=c){if(null!=Ijb(a))return!1;b=!c}return b},Ljb=function(a){return a.ea.N("html5_honor_caption_availabilities_in_audio_track")&&!a.ob},Mjb=function(a){var b;
a.yc?b=new Z4(a.ea,a.videoData,a.player.getAudioTrack(),a.player):a.ob?b=new X4(a.videoData.j,a.player):a.hc?b=new g.BT(a.ea,a.videoData,a.player.getAudioTrack()):b=new g.GT(a.ea,a.videoData.Id,a.videoData.videoId,g.TAa(a.videoData),a.videoData.Km,a.videoData.eventId);return b},D5=function(a,b){if(a.j){if(a.S&&a.S.D)return a.S.D;
g.jO(a.videoData)&&(b=!0);b||(b=a.zc?!1:a.hc?!1:!0);b=b||Njb(a);b=g.yT(a.j.j,b);var c=null;if(g.mM(a.ea)){var d=a.J.isInline()?void 0:g.IB("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.ea.captionsLanguagePreference,g.ZN(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.IM(b[m])===l)return b[m];m=l.split("-")[0];for(var n=0;n<b.length;n++)if(a.ea.N("html5_enable_same_language_id_matching")){if(g.IM(b[n]).split("-")[0]===
l.split("-")[0])return b[n]}else if(g.IM(b[n])===m)return b[n]}}if(f&&a.j&&(e=a.j.D,e.length))for(e=g.v(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.ea.captionsLanguagePreference,g.ZN(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.IM(b[f])===d[e])return b[f];d=null;a.S&&a.S.C&&(d=a.S.C);d||(d=b.find(function(p){return p.isDefault})||null);
d||(d=b[0]||C5(a));!d||!c||a.ea.N("html5_enable_same_language_id_matching")&&g.IM(d).split("-")[0]===c.languageCode.split("-")[0]||(d=rib(d,c));return d}return null},C5=function(a){return a.S&&a.S.j},E5=function(a){var b=C5(a);
return!!b&&a.B===b},Ojb=function(a){g.yT(a.j.j,!0);
var b=qib(a.player.getAudioTrack(),g.mM(a.ea)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=D5(a,a.qa):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&B5(a)?c=C5(a):Jjb(a)||a.qa||Kjb(a)?c=D5(a,a.qa):B5(a)&&(c=C5(a));if(a.D||a.Ca){var d=g.yT(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.bf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.GM(f));h.setAttribute("srclang",g.IM(f));h.setAttribute("id",f.toString());a.Ca||h.setAttribute("src",a.j.Tv(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.J.Re();c.YB(b);c=c.Bb();a.Cb&&a.Ha.V(c.textTracks,"change",a.I9)}else!a.B&&c&&F5(a,c),a.player.Ra("onCaptionsTrackListChanged"),a.player.Ra("onApiChange")},Pjb=function(a,b){var c=a.J.Re().Bb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},F5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.qa=c,a.qa&&(g.mM(a.ea)?G5(a,!!b):H5(a,!!b)));a.B=b;B5(a)&&(a.B=C5(a));var d;Qjb(a,null!=(d=a.B)?d:void 0);a.load()},Sjb=function(a,b){if(b instanceof c5){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=Rjb(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Ya[c]||(a.Ya[c]=[]),a.Ya[c].push(b)},Rjb=function(a,b){var c=Tjb(a);
if(!c)return null;var d=a.B?g.IM(a.B):null;d&&g.Scb.test(d)&&(b.params.Hi=1);var e=a.wb.getPlayerSize();d=e.height*a.ma.height;e=e.width*a.ma.width;"google-live"!==a.ea.playerStyle||a.C.isDefault||Object.assign(b.params,a.C);switch(null!=b.params.eA?b.params.eA:1<b.j.length?1:0){case 1:return new $4(b,a.C,a.G,c.width,c.height,e,d,a.ea.experiments,a.qK.bind(a),a.J);case 2:return new a5(b,a.C,a.G,c.width,c.height,e,d,a.ea.experiments,a.qK.bind(a),a.J);default:return new Y4(b,a.C,a.G,c.width,c.height,
e,d,a.ea.experiments,a.qK.bind(a),a.J)}},Hjb=function(a,b,c){c=void 0===c?!1:c;
var d=I5.Ye;a.C={};Object.assign(a.C,I5);a.C.Ye={};Object.assign(a.C.Ye,d);a.G={Ye:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;j5.test(f);e.Ye.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;j5.test(f);e.Ye.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||I5.windowColor;j5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ye.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Ye.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Ye;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ye.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=I5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ye.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ye.fontFamily=f;a.loaded&&a.wR();c&&g.HB("yt-player-caption-display-settings",b,2592E3)},Vjb=function(a,b,c){b&&!a.W?(b=Tib({Hi:0,
lang:"en-GB"}),a.W=[b,new b5(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.jf(a.W)):!b&&a.W&&(Ujb(a,a.W),a.W=null)},Ujb=function(a,b){a.player.Tp(b);
b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.Hb(a.Ga,c.value);g.ar(a.Oa)},Qjb=function(a,b){a.ea.N("html5_modify_caption_vss_logging")&&(a.videoData.wB=b)},Tjb=function(a){var b=a.wb.getVideoContentRect(!0).height,c=a.wb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ma.height;c*=a.ma.width;return{width:c,height:b}},H5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},G5=function(a,b){a.J.isInline()||g.HB("yt-player-sticky-caption",b,2592E3)},Ijb=function(a){if(!a.J.isInline())return g.IB("yt-player-sticky-caption")},Gjb=function(a){var b,c=!(null==(b=a.J.Re())||!b.kF());
return a.fb&&c&&!a.ob},Njb=function(a){return a.ea.N("web_deprecate_always_includes_asr_setting")&&g.mM(a.ea)?!0:!!g.PB(g.OB(),66)};
g.EW.prototype.NC=g.ca(41,function(a){var b=2;this.Ca.has(a)?b=0:g.IUa(this,a)&&(b=1);return b});
g.OY.prototype.NC=g.ca(40,function(a){return this.jd.NC(a)});
g.EW.prototype.sF=g.ca(39,function(a,b,c){this.Va.set(a,{Us:b,wy:c})});
g.OY.prototype.sF=g.ca(38,function(a,b,c){this.jd.sF(a,b,c)});
g.AT.prototype.QP=g.ca(31,function(){return!1});
g.AT.prototype.Rt=g.ca(30,function(){});
g.BT.prototype.Rt=g.ca(29,function(a,b,c){var d=this;this.isDisposed();b=this.Tv(a,b);this.ws();this.B=g.xA(b,{format:"RAW",onSuccess:function(e){d.B=null;c(e.responseText,a)},
withCredentials:!0})});
g.GT.prototype.Rt=g.ca(28,function(a,b,c){var d=this;this.isDisposed();b=this.Tv(a,b);this.ws();this.B=g.xA(b,{format:"RAW",onSuccess:function(e){d.B=null;c(e.responseText,a)},
withCredentials:!0})});
g.hT.prototype.Ly=g.ca(27,function(){for(var a=g.Le(document,"track",void 0,this.j),b=0;b<a.length;b++)g.gf(a[b])});
g.rW.prototype.Ly=g.ca(26,function(){this.mediaElement.Ly()});
g.hT.prototype.lF=g.ca(25,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.rW.prototype.lF=g.ca(24,function(){return this.mediaElement.lF()});
g.hT.prototype.kF=g.ca(23,function(){return!!this.j.textTracks});
g.rW.prototype.kF=g.ca(22,function(){return this.mediaElement.kF()});
g.hT.prototype.YB=g.ca(21,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.rW.prototype.YB=g.ca(20,function(a){this.mediaElement.YB(a)});
g.GY.prototype.cD=g.ca(10,function(){return this.W});
g.UZ.prototype.cD=g.ca(9,function(){var a;return(null==(a=g.eS(this))?void 0:a.pz())||null});
g.oS.prototype.pz=g.ca(8,function(){return this.app.cD()});
g.HZ.prototype.pz=g.ca(7,function(){var a;return(null==(a=this.Ea)?void 0:a.cD())||null});
g.nI.prototype.oH=g.ca(3,function(a){return(a=this.cn(a))?a.j:0});
g.gva.prototype.oH=g.ca(2,function(){return 0});
var vib=/#(.)(.)(.)/,uib=/^#(?:[0-9a-f]{3}){1,2}$/i,Cib={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};W4.prototype.contains=function(a){a=g.Tb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
W4.prototype.length=function(){return this.segments.length/2};
g.x(zib,g.G);g.k=zib.prototype;g.k.ya=function(){g.G.prototype.ya.call(this);this.C&&this.C.cancel()};
g.k.pA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Jd();var b=this.j;this.j=g.xb(this.ma.Jq(a).ib);b!==this.j&&this.W&&this.W()};
g.k.reset=function(){this.D=new W4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.bX=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Es(a);if(a&&!this.C&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.NB(a);var b=a.ib[0],c;if(null==(c=this.player.getVideoData())?0:c.enableServerStitchedDai)if(c=this.player.pz()){var d=b.j.info.id,e=b.Qa,f=a.ib[0].D;if(this.policy.Ha){if(c=c.Dt(f,e,d,3))a.D=c}else if(d=c.jp(f,e,d,3))if(c=c.NC(e),0===c)d&&(a.j=new g.hI(d));else if(2===c){this.S.start();Aib(this)&&this.seekTo(this.player.getCurrentTime());
return}}(this.policy.UB?b.j.index.zp(b.Qa):a.ib[0].duration)?(this.D.contains(a.ib[0].Qa)||Bib(this,a),this.j=g.xb(a.ib)):Aib(this)&&this.seekTo(this.player.getCurrentTime())}this.S.start()};
g.x(X4,g.AT);g.k=X4.prototype;g.k.Rt=function(a,b,c){var d=this;this.ws();b=Eib(this,a.getId());b||(b=a.languageCode,b=this.B.isManifestless?Fib(this,b,"386"):Fib(this,b));if(b){var e=1E3*(b.index.oH(b.index.qn())-b.index.getStartTime(b.index.qn())),f=new g.DOa(this.ea);this.C=new zib(f,this.J,b,function(h,l){c(h,a,l,e)},this.K||g.FJ(b.info),function(){d.C&&d.C.reset();
d.G=!0})}};
g.k.QP=function(){var a=this.G;this.G=!1;return a};
g.k.Tz=function(a){var b=this.K?[new g.FM({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.FM({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.B.isManifestless?Dib(this,"386"):Dib(this);b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.zT(this.j,c.value);a()};
g.k.ws=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Tv=function(){return""};
var j5=/^#(?:[0-9a-f]{3}){1,2}$/i,Gib=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Ra("yt.msgs_",Gib);var Kib=["left","right","center","justify"];g.x(Y4,g.Y);g.k=Y4.prototype;g.k.E0=function(a,b){this.ob=a;this.sb=b;var c=g.Ho(this.element,this.element.parentElement);this.wb=a-c.x;this.Cb=b-c.y};
g.k.D0=function(a,b){if(a!==this.ob||b!==this.sb){g.ir(this.element,"ytp-dragging")||g.jr(this.element,"ytp-dragging");var c=g.Jo(this.element);a=a-this.wb-.02*this.playerWidth;var d=b-this.Cb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.qe(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.qe(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.qe(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.qe(c,0,1);this.B.params.fm=b;this.B.params.qo=c;this.B.params.jk=
a;this.B.params.isDefault=!1;this.j.fm=b;this.j.qo=c;this.j.jk=a;this.j.isDefault=!1;this.Ca.fm=b;this.Ca.qo=c;this.Ca.jk=a;this.Ca.isDefault=!1;this.ZY()}};
g.k.C0=function(){g.lr(this.element,"ytp-dragging")};
g.k.ZY=function(){this.UA(this.K)};
g.k.getType=function(){return this.type};
g.k.UA=function(a){var b=Math.min(this.tV(),this.maxWidth),c=this.sV(),d="";3===this.B.params.Hi&&(d="rotate(180deg)");g.yo(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.CL(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.jk+2,f=this.j.fm;switch(f){case 0:case 3:case 6:(b=this.j.Ye.fontSizeIncrement)&&0<b&&2!==this.j.Hi&&3!==
this.j.Hi&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.qo+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.yo(this.element,
d);if(this.G){c=this.D.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.CL=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ga||this.K.length>b)b=0,this.Ga=!1,this.K=[],this.S=this.Pa=this.Oa=null,g.ef(this.D);for(;b<a.length;b++)Pib(this,a[b])};
g.k.tV=function(){return 0};
g.k.sV=function(){return 0};
g.k.toString=function(){return g.Y.prototype.toString.call(this)};g.x(Z4,g.AT);Z4.prototype.Rt=function(a,b,c){tib(this.videoData.videoId,a.vssId,c)};
Z4.prototype.Tz=function(a){if(this.audioTrack)for(var b=g.v(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.zT(this.j,c.value);a()};g.x($4,Y4);$4.prototype.CL=function(a){var b=this.B.j;Y4.prototype.CL.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Wjb);var e=c.j;var f=d}Pib(this,c,d)}};
var Wjb={X5:!0};g.x(a5,Y4);g.k=a5.prototype;g.k.ZY=function(){g.dr(this.fb)};
g.k.a9=function(){g.lr(this.element,"ytp-rollup-mode");this.UA(this.zc,!0)};
g.k.sV=function(){return this.C?this.ra:this.qa};
g.k.tV=function(){return this.C?this.qa:this.ra};
g.k.UA=function(a,b){this.zc=a;if(this.B.params.Mr){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.K.concat(a.slice(c)));this.hc=this.ra;this.qa=this.ra=0;Y4.prototype.UA.call(this,a);Sib(this,b)}Y4.prototype.UA.call(this,a)};g.x(b5,g.RG);b5.prototype.toString=function(){return g.RG.prototype.toString.call(this)};g.x(c5,g.RG);c5.prototype.toString=function(){return g.RG.prototype.toString.call(this)};
var d5=0;g.x(e5,g.G);e5.prototype.B=function(){return[]};
e5.prototype.reset=function(){};g.x(f5,e5);f5.prototype.reset=function(){this.S={};this.C=this.j=null;this.K=!0};
f5.prototype.B=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.v(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.v(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=h5(a,"b");
null!=l&&(h.bold=l);l=h5(a,"i");null!=l&&(h.italic=l);l=h5(a,"u");null!=l&&(h.underline=l);l=i5(a,"et");null!=l&&(h.charEdgeStyle=l);l=i5(a,"of");null!=l&&(h.offset=l);l=k5(a,"bc");null!=l&&(h.background=l);l=k5(a,"ec");null!=l&&(h.WL=l);l=k5(a,"fc");null!=l&&(h.color=l);l=i5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=g5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=g5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=g5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=i5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.fg=10<l?l-1:l);a=i5(a,"hg");null!=a&&(h.pW=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.ma[c]=Wib(this,a);break;case "wp":c=a.getAttribute("id"),this.W[c]=Xib(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.v(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=Yib(this,a,b,!1);(a=this.S[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.S[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.G;
h=!!h5(a,"a");l=(g5(a,"t")||0)+l;var m=g5(a,"d")||5E3;h||(!this.K&&this.C&&this.C.windowId===f&&this.C.end>l&&(this.C.end=l),this.C&&"\n"===this.C.text&&(this.C.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.K=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var u=q[t],y=void 0;0<t&&(h=!0);var A=void 0;1===u.nodeType&&(A=u);if(A&&"s"===A.tagName){if((u=(u=A.getAttribute("p"))?this.pens[u]:null)&&u.fg&&(1===u.fg?(u=q.slice(t,t+
4),4===u.length&&(y=Vib(l,m,f,h,n,u,this.pens),t+=3)):y=Vib(l,m,f,h,n,[A],this.pens)),!y){var E=A;y=l;A=m;u=f;var L=h,I=n,F=E.textContent?E.textContent:"",R=E.getAttribute("p");R=R?this.pens[R]:null;E=g5(E,"t")||0;y=new b5(y+E,A-E,I,u,F,L,R)}}else y=new b5(l,m,n,f,u.textContent||"",h,p);c.push(y);this.C=y}if(0<c.length)for(c[0].windowId===this.G&&(this.j=Yib(this,a,b,!0),d.push(this.j)),a=g.v(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Xjb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.x(l5,e5);l5.prototype.reset=function(){this.C.clear()};
l5.prototype.B=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.v(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.WL=m5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=m5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=m5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.fg=10<h?h-1:h,f.po=Xjb.get(f.fg));e.hgHorizGroup&&(f.pW=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.v(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.G.get(h)):Object.assign(f,
this.K),void 0!==e.mhModeHint&&(f.eA=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Hi=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.cR=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=m5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.G.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.v(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.D.get(h)),void 0!==e.ahHorPos&&
(f.jk=e.ahHorPos),void 0!==e.apPoint&&(f.fm=e.apPoint),void 0!==e.avVerPos&&(f.qo=e.avVerPos),void 0!==e.ccCols&&(f.Qs=e.ccCols),void 0!==e.rcRows&&(f.Mr=e.rcRows),this.D.set(a++,f);if(c.events){a=[];c=g.v(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=Zib(this,l,d,e,f),a.push(d),this.C.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+d5++,h=Zib(this,l,d,e,f),a.push(h),this.C.set(f,h));0===e&&(e=5E3);h=this.C.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if(2===(null!=h.params.eA?h.params.eA:1<h.j.length?1:0)&&m&&"\n"===u)continue;if(t=A&&1===A.fg)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var E=p[t+1].pPenId;(E=this.j.get(E))&&E.fg&&2===E.fg?(E=p[t+2].pPenId,E=this.j.get(E),!E||!E.fg||3>E.fg?t=!1:(E=p[t+3].pPenId,t=(E=this.j.get(E))&&
E.fg&&2===E.fg?!0:!1)):t=!1}if(t){y=p[l+1].utf8;t=p[l+3].utf8;E=p[l+2].utf8;var L=this.j.get(p[l+2].pPenId);u=Uib(u,y,E,t,L);m=new b5(d,e,n,f,u,m,A);l+=3}else m=new b5(d+y,e-y,n,h.id,u,m,A||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};ajb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
ajb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var bjb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];n5.prototype.set=function(a){this.type=a};
n5.prototype.get=function(){return this.type};
o5.prototype.clear=function(){this.state=0};
o5.prototype.update=function(){this.state=2===this.state?1:0};
o5.prototype.Ie=function(){return 0!==this.state};
o5.prototype.matches=function(a,b){return this.Ie()&&a===this.qv&&b===this.Ls};
gjb.prototype.reset=function(){this.timestamp=this.j=0};
p5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
p5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
p5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var hjb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],ijb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],jjb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],kjb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];ojb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.S;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.S.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
$ib.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};sjb.prototype.D=function(){};g.x(u5,sjb);u5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+d5++;c=c/1E3-this.K;d=d/1E3-this.K;a=new c5(c,d-c,5,f,{textAlign:0,fm:0,jk:2.5*b,qo:5.33*a});e=new b5(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.x(x5,e5);x5.prototype.B=function(a){a=new u5(a,a.byteLength,this.C);if(tjb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.C=w5(a)*(1E3/45):1===a.version&&(a.C=4294967296*w5(a)+w5(a)),a.G=v5(a);0<a.G;a.G--){var b=v5(a),c=v5(a),d=v5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.C,type:this.track,tU:c,uU:d,order:b.j.length}))}fjb(this.j,a);return a.B}return[]};
x5.prototype.reset=function(){this.j.clear()};g.x(y5,e5);
y5.prototype.B=function(a,b){var c=[];a=a.split(Yjb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!Zjb.test(e)){var h=$jb.exec(e);if(h&&4<=h.length){var l=wjb(h[1]),m=wjb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,u="";n=g.v(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var A=y[1];switch(y[0]){case "line":y=A.split(",");y[0].endsWith("%")&&(p=y[0],h.qo=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
A.split(",");t=y[0];h.jk=Number.parseInt(t,10);2===y.length&&(u=y[1].trim());break;case "align":switch(A){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.jk=0;break;case 1:h.jk=100;break;case 2:h.jk=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.fm=q}e=e.substring($jb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=xjb(l,m,5,u),m=new b5(l,m,5,f.id,h,!1,g.ed(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(akb),1===q.length?(h=5,u=xjb(l,m,h,u)):(p=h=6,u=Object.assign({Qs:32},u),u=new c5(l,m,p,"_"+d5++,u)),c.push(u),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(y=g.Qab("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(A=y.createElement("span"),A.appendChild(y.createTextNode(n))):A=y.firstChild,vjb(this,p,m-(p-l),h,u,0<t,A,e,c)):p=wjb(n)+f}$jb.lastIndex=0}}return c};
var Zjb=/^NOTE/,Yjb=/(?:\r\n|\r|\n){2,}/,$jb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),akb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.sW.rD(y5,{B:"wvppt"});g.x(z5,g.G);z5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
z5.prototype.reset=function(){this.parser&&this.parser.reset()};
z5.prototype.ya=function(){g.G.prototype.ya.call(this);this.clear()};var I5={windowColor:"#080808",windowOpacity:0,textAlign:2,fm:7,jk:50,qo:100,isDefault:!0,Ye:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.x(A5,g.xT);g.k=A5.prototype;g.k.ya=function(){if(this.D||this.Ca){var a=this.J.Re();a&&!a.isDisposed()&&a.Ly()}else Vjb(this,!1);g.xT.prototype.ya.call(this)};
g.k.Yw=function(){if(this.fb)return this.D||this.Ca;var a=this.player.getAudioTrack();if(Ljb(this)){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=qib(a,g.mM(this.ea));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?B5(this):Jjb(this)||B5(this)?!0:Kjb(this)};
g.k.load=function(){var a=this;g.xT.prototype.load.call(this);this.S=this.player.getAudioTrack();this.j?this.B&&(this.kb.clear(),this.D?Pjb(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Rt(this.B,"json3",function(b,c,d,e){if(b){var f;Qjb(a,null!=(f=a.B)?f:void 0);a.j.QP()&&(a.Ga=[],a.J.Ue("captions"),g.ar(a.Oa),a.kb.reset());b=Djb(a.kb,b,c,d,e);a.player.jf(b,void 0,a.ob);!a.qa||a.Ca||E5(a)||g.fM(a.ea)||g.ZL(a.ea)||g.$L(a.ea)||"shortspage"===a.ea.Va||a.player.isInline()||(g.er(a.Pa),b=
Tib({fm:0,jk:5,qo:5,Mr:2,textAlign:0,Hi:0,lang:"en-GB"}),a.Va=[b],c=["Click "," for settings"],a.sb||(d=new g.vQ(g.TFa()),g.H(a,d),a.sb=d.element),d=b.end-b.start,(e=g.GM(a.B))&&a.Va.push(new b5(b.start,d,0,b.id,e)),a.Va.push(new b5(b.start,d,0,b.id,c[0]),new b5(b.start,d,0,b.id,a.sb,!0),new b5(b.start,d,0,b.id,c[1],!0)),a.player.jf(a.Va),g.cr(a.Pa));!a.qa||a.Ca||E5(a)||(g.mM(a.ea)?G5(a,!0):H5(a,!0),a.S&&(a.S.D=a.B),a.player.Bo());a.qa=!1}}),this.D||this.Ca||E5(this)||this.player.Ra("captionschanged",
g.HM(this.B))):(this.j=Mjb(this),g.H(this,this.j),this.j.Tz(function(){Ojb(a)}))};
g.k.unload=function(){this.D&&this.B?Pjb(this,!1):(this.Pa&&g.er(this.Pa),this.player.Ue("captions"),this.Ga=[],this.j&&this.j.ws(),this.kb.clear(),this.W&&this.player.jf(this.W),this.wR());g.xT.prototype.unload.call(this);this.player.Bo();this.player.Ra("captionschanged",{})};
g.k.create=function(){this.Yw()&&this.load();var a;a:{var b,c,d;if(this.ea.N("suggest_caption_correction_menu_item")&&this.ea.N("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.v(b),e=a.next();!e.done;e=
a.next())if(e=e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.J.va("showpromotooltip",this.K.element)};
g.k.I9=function(){for(var a=this.J.Re().Bb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.yT(this.j.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.B:null)!==b&&F5(this,b,!0)};
g.k.Iaa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ga.push(a);g.ar(this.Oa)};
g.k.onCueRangeExit=function(a){g.Hb(this.Ga,a);this.j instanceof X4&&this.j.K&&this.player.Tp([a]);g.ar(this.Oa)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.w$=function(){Ujb(this,this.Va);this.Va=null};
g.k.uR=function(){var a=this;if(!this.Vb||!this.D){this.Oa.stop();g.dba(this.Ya);this.Ga.sort(g.Ora);var b=this.Ga;if(this.W){var c=g.sp(b,function(f){return-1===this.W.indexOf(f)},this);
c.length&&(b=c)}b=g.v(b);for(c=b.next();!c.done;c=b.next())Sjb(this,c.value);b=g.v(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={cw:c.cw,Xm:c.Xm},d=b.next()){var e=g.v(d.value);d=e.next().value;e=e.next().value;c.cw=d;c.Xm=e;this.Ya[c.cw]?(c.Xm.element.parentNode||(c.Xm instanceof a5||c.Xm instanceof $4||g.Yc(this.ra,function(f){return function(h,l){l!==f.cw&&h.B.params.fm===f.Xm.B.params.fm&&h.B.params.jk===f.Xm.B.params.jk&&h.B.params.qo===f.Xm.B.params.qo&&(h.dispose(),delete a.ra[l]);
return l===f.cw}}(c),this),this.K.element.appendChild(c.Xm.element)),c.Xm.UA(this.Ya[c.cw])):(c.Xm.dispose(),delete this.ra[c.cw])}}};
g.k.C$=function(){Hjb(this,{},!0);this.player.Ra("captionssettingschanged")};
g.k.o5=function(){var a=I5.Ye;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:I5.windowColor,windowOpacity:I5.windowOpacity};var b=xib()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.u_=function(a,b){var c={};Object.assign(c,xib());Object.assign(c,a);Hjb(this,c,b);this.player.Ra("captionssettingschanged")};
g.k.wR=function(){!this.D&&this.loaded&&(g.Vc(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.uR())};
g.k.Jh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.qe(b,-2,4);this.u_({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&F5(this,this.B,!0);break;case "stickyLoading":void 0!==b&&this.ea.K&&(g.mM(this.ea)?G5(this,!!b):H5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.Xa(b))break;if(g.ed(b)){F5(this,null,!0);break}a=g.yT(this.j.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?rib(e,b.translationLanguage):e)}this.VJ(b.position);!c||c===this.B&&this.loaded||(b=g.wwa(),a=g.IM(c),b.length&&a===b[b.length-1]||(b.push(a),g.HB("yt-player-caption-language-preferences",b)),g.mM(this.ea)&&!this.J.isInline()&&g.HB("yt-player-caption-sticky-language",a,2592E3),F5(this,c,!0))}else return this.loaded&&this.B&&!E5(this)?g.HM(this.B):{};return"";case "tracklist":return this.j?g.Cn(g.yT(this.j.j,!(!b||!b.includeAsr)),function(f){return g.HM(f)}):
[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||void 0===b||Vjb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||Vjb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.wwa()}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.ea.K&&a.push("stickyLoading");return a};
g.k.Lq=function(){var a=this.B;if(this.ea.N("html5_modify_caption_vss_logging")){var b;return(a=null!=(b=this.videoData.wB)?b:null)?{cc:g.yya(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.IM(a)),{cc:b}):{}};
g.k.waa=function(){this.isSubtitlesOn()?(g.mM(this.ea)?G5(this,!1):H5(this,!1),Qjb(this),this.unload(),B5(this,!0)&&F5(this,C5(this),!1)):this.b_()};
g.k.b_=function(){this.isSubtitlesOn()||F5(this,E5(this)||!this.B?D5(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!E5(this)};
g.k.C7=function(){var a=E5(this);B5(this,a)?F5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),Ljb(this)&&(this.qa=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Yw()&&(a?F5(this,D5(this),!1):this.load()))};
g.k.VJ=function(a){a&&(this.ma={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.ma.top+"%",this.K.element.style.left=100*this.ma.left+"%",this.K.element.style.width=100*this.ma.width+"%",this.K.element.style.height=100*this.ma.height+"%",this.K.element.style.position="absolute",a=Tjb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.k8=function(){var a=this.J.Re();a&&!a.isDisposed()&&a.Ly();this.J.isFullscreen()?(this.D=this.fb=!0,this.loaded&&Ojb(this)):(this.fb="3"===this.ea.controlsType,this.D=Gjb(this));F5(this,this.B)};
g.k.qK=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Ra("innertubeCommand",d)};
g.sW.rD(A5,{uR:"smucd"});g.wT("captions",A5);})(_yt_player);
